
export const UPDATE_CONTRACT_ADDRESS_INFO = 'UPDATE_CONTRACT_ADDRESS_INFO';
export const DROP_CONTRACT_ADDRESS_INFO = 'DROP_CONTRACT_ADDRESS_INFO';
export const CREATE_CONTRACT_ADDRESS_INFO = 'CREATE_CONTRACT_ADDRESS_INFO';

export const SET_CONTRACT_PRICE = 'SET_CONTRACT_PRICE';
export const SET_TOTAL_ISSUED = 'SET_TOTAL_ISSUED';