
export const UPDATE_CONTRACT_ADDRESS_INFO = 'UPDATE_CONTRACT_ADDRESS_INFO';
export const DROP_CONTRACT_ADDRESS_INFO = 'DROP_CONTRACT_ADDRESS_INFO';
export const CREATE_CONTRACT_ADDRESS_INFO = 'CREATE_CONTRACT_ADDRESS_INFO';

export const SET_CONTROL_CONTRACT_PRICE = 'SET_CONTROL_CONTRACT_PRICE';