module.exports = {
    BondsOrders: require('./BondsOrders'),
    BondsOrdersHistory: require('./BondsOrdersHistory'),
    NeutrinoOrders: require('./NeutrinoOrders'),
    NeutrinoPrices: require('./NeutrinoPrices'),
    NeutrinoBalances: require('./NeutrinoBalances'),
    NeutrinoWithdraw: require('./NeutrinoWithdraw'),
    RpdBalances: require('./RpdBalances'),
    RpdHistoryBalances: require('./RpdHistoryBalances'),
    RpdUserBalances: require('./RpdUserBalances'),
    RpdUserHistoryBalances: require('./RpdUserHistoryBalances'),
    RpdProfit: require('./RpdProfit'),
    RpdNextIndex: require('./RpdNextIndex'),
    RpdIndexNumbers: require('./RpdIndexNumbers'),
    RpdIsClaimed: require('./RpdIsClaimed'),
    ControlConfig: require('./ControlConfig'),
};
